apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#            - key: cpu
#              operator: In
#              values:
#                - fast
#                - veryFast
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: cpu
                operator: In
                values:
                  - fast
          weight: 2
        - preference:
            matchExpressions:
              - key: cpu
                operator: In
                values:
                  - slow
          weight: 1

