apiVersion: v1
kind: Service
metadata:
  name: traefik

spec:
  ports:
    - protocol: TCP
      name: nginxweb
      port: 8000
    - protocol: TCP
      name: admin
      port: 8080
    - protocol: TCP
      name: nginxsecure
      port: 4443
  selector:
    app: traefik
