apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: busybox
      command: [ "/bin/sh", "-c", "echo $BUSY_NAME ; sleep 3600;" ]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: my-secret
