apiVersion: v1
kind: Pod
metadata:
  name: probe-exec-nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      ports:
        - containerPort: 80
      command: [ "/bin/sh" ]
      args:
        - -c
        - sleep 30;nginx -g "daemon off;"
      livenessProbe:
        exec:
          command:
            - ls
            - /var/run/nginx.pid
        initialDelaySeconds: 5
        periodSeconds: 4
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1
