apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment-app
  namespace: namespace1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod-app
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod-app
      namespace: namespace1
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80
