apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "0.5"
        limits:
          cpu: "1"
