apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
    - name: redis
      image: redis:5.0.10
      ports:
        - containerPort: 6379
      command: ["redis-server"]
      args: ["--appendonly yes"]
