apiVersion: v1
kind: Pod
metadata:
  name: init-container-pod
spec:
  containers:
    - name: myapp-container
      image: busybox:1.28
      command: [ 'sh', '-c', 'echo The app is running! && sleep 3600' ]
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: [ 'sh', '-c', 'echo init-myservice is running! && sleep 5' ]
    - name: init-mydb
      image: busybox:1.28
      command: [ 'sh', '-c', 'echo init-mydb is running! && sleep 10' ]
