server:
  port: 8099

#数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # &allowMultiQueries=false
    url: jdbc:mysql://localhost:3306/java-private-project?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

#指定Mybatis映射文件位置
mybatis:
  mapper-locations: classpath*:/dao/**Dao.xml

#SQL日志打印
logging:
  level:
    com.codeshu.dao: DEBUG
