apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
    - name: busybox-container
      image: busybox:1.28
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo 'Hello dynamic!' >> /data/index2.html; sleep 1; done"]
      volumeMounts:
        - name: nfs-volume
          mountPath: /data
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
