apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: busybox
      command: [ "/bin/sh", "-c", "echo $BUSY_NAME ; sleep 3600;" ]
      env:
        - name: BUSY_NAME
          valueFrom:
            configMapKeyRef:
              name: my-config-map
              key: key1
