apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    otherApp: otherAppPod
spec:
  containers:
    - name: mysql
      image: mysql/mysql-server:8.0
      ports:
        - containerPort: 3306
