apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      lifecycle:
        postStart:
          exec:
            command: [ "/bin/sh","-c","echo postStart >> /start.txt" ]
        preStop:
          exec:
            command: [ "/bin/sh","-c","echo postStop >> /stop.txt && sleep 5" ]
      ports:
        - containerPort: 80
