apiVersion: v1
kind: Pod
metadata:
  name: probe-httpget-nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.19
      ports:
        - containerPort: 80
      command: [ "/bin/sh" ]
      args:
        - -c
        - sleep 7;nginx -g "daemon off;"
      livenessProbe:
        httpGet:
          port: 80
          path: /index.html
        initialDelaySeconds: 5
        periodSeconds: 4
        timeoutSeconds: 1
        failureThreshold: 3
        successThreshold: 1
