apiVersion: batch/v1
kind: Job
metadata:
  name: perl-job
spec:
  template:
    spec:
      containers:
        - name: perl
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  # 当前任务出现失败 最大的重试次数
  backoffLimit: 4
